from setuptools import setup, find_packages

setup(
    name='mylibpkgset',
    version='0.0.1',
    description='my pypi lib pkg unit set',
    author='du7ec',
    author_email='dutec6834@gmail.com',
    url='https://github.com/FarAway6834/mylibpkgset',
    packages=find_packages(exclude=[]),
    install_requires=['stxxp', 'builtinset'],
    keywords=['my', 'pypi', 'lib', 'pkg', 'init', 'set', 'mylibpkgset'],
    python_requires='>=2.0',
    package_data={},
    classifiers=[
        'Programming Language :: Python :: 2.0',
        'Programming Language :: Python :: 2.1',
        'Programming Language :: Python :: 2.2',
        'Programming Language :: Python :: 2.3',
        'Programming Language :: Python :: 2.4',
        'Programming Language :: Python :: 2.5',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3.0',
        'Programming Language :: Python :: 3.1',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Python :: 3.14',
    ],
)